Repository modern-agile-team/8term-coko-back, pull requests merged in 2024-12, with the labels that each got.

#40 items API Swagger 설정
  package-lock.json
  src/items/dto/item-changeStatus.dto.ts
  src/items/items.controller.ts
  src/items/items.swagger.ts
  src/main.ts
Labels: docs, feat, API

#43 user 삭제시 서버가 꺼지던 에러 수정
  prisma/migrations/20241208080451_cascade_token/migration.sql
  prisma/schema.prisma
  src/users/controllers/users.controller.ts
  src/users/services/users.service.ts
Labels: bug, fix

#37 repository 클래스 나누기 + reqDTO , resDTO 생성 후 사용
  src/app.module.ts
  src/parts/dto/create-part.dto.ts
  src/parts/dto/res-part.part.dto.ts
  src/parts/dto/update-part.dto.ts
  src/parts/entities/part.entity.ts
  src/parts/parts.controller.ts
  src/parts/parts.module.ts
  src/parts/parts.repository.ts
  src/parts/parts.service.ts
  src/parts/parts.swagger.ts
  src/progress/dto/res-progress.dto.ts
  src/progress/entities/progress.entity.ts
  src/progress/progress.controller.ts
  src/progress/progress.module.ts
  src/progress/progress.repository.ts
  src/progress/progress.service.ts
  src/progress/progress.swagger.ts
  src/quizzes/dto/res-quiz.dto.ts
  src/quizzes/entities/quizzes.entity.ts
  src/quizzes/quizzes.controller.ts
  src/quizzes/quizzes.module.ts
  src/quizzes/quizzes.repository.ts
  src/quizzes/quizzes.service.ts
  src/quizzes/quizzes.swagger.ts
  src/sections/dto/res-section.dto.ts
  src/sections/dto/update-section.dto.ts
  src/sections/entities/section.entity.ts
  src/sections/sections.controller.ts
  src/sections/sections.module.ts
  src/sections/sections.repository.ts
  src/sections/sections.service.ts
  src/sections/sections.swagger.ts
Labels: API, refactor

#45 part progress API 작성
  prisma/migrations/20241209140233_part_progress_create/migration.sql
  prisma/schema.prisma
  src/app.module.ts
  src/common/util/type-utils.ts
  src/part-progress/dto/create-part-progress.dto.ts
  src/part-progress/dto/res-part-progress.dto.ts
  src/part-progress/entities/part-progress.entity.ts
  src/part-progress/part-progress.controller.spec.ts
  src/part-progress/part-progress.controller.ts
  src/part-progress/part-progress.module.ts
  src/part-progress/part-progress.repository.ts
  src/part-progress/part-progress.service.spec.ts
  src/part-progress/part-progress.service.ts
  src/part-progress/part-progress.swagger.ts
  src/progress/progress.swagger.ts
  src/quizzes/dto/create-quiz.dto.ts
  src/quizzes/entities/quizzes.entity.ts
Labels: feat, API

#50 section/{id}/users/{id}/part-status API 작성
  src/part-progress/dto/create-part-progress.dto.ts
  src/sections/dto/res-section.dto.ts
  src/sections/sections.controller.ts
  src/sections/sections.repository.ts
  src/sections/sections.service.ts
  src/sections/sections.swagger.ts
Labels: feat, modify, API

#54 Section part 에 새로운 order 속성 추가와 관련 api 작성
  prisma/migrations/20241224014130_create_order_attribute/migration.sql
  prisma/schema.prisma
  src/parts/dto/res-part.part.dto.ts
  src/parts/dto/update-part-order.dto.ts
  src/parts/entities/part.entity.ts
  src/parts/parts.controller.ts
  src/parts/parts.repository.ts
  src/parts/parts.service.ts
  src/parts/parts.swagger.ts
  src/sections/dto/res-section.dto.ts
  src/sections/dto/update-section-order.dto.ts
  src/sections/entities/section.entity.ts
  src/sections/sections.controller.ts
  src/sections/sections.repository.ts
  src/sections/sections.service.ts
  src/sections/sections.swagger.ts
Labels: feat, modify, API

#59 파트의 순서(order) 값이 중첩되지 않았던 오류 수정
  src/parts/parts.repository.ts
  src/parts/parts.service.ts
Labels: bug, modify
