Repository modern-agile-team/8term-coko-back, pull requests merged in 2024-10, with the labels that each got.

#10 로컬에서 간단하게 쓸 postgres 데이터베이스
  docker-compose.yml
Labels: setting

#12 User api 부분 생성
  .github/PULL_REQUEST_TEMPLATE.md
  package-lock.json
  package.json
  prisma/migrations/20241002122924_init/migration.sql
  prisma/migrations/20241002123657_init/migration.sql
  prisma/migrations/20241002124953_init/migration.sql
  prisma/migrations/20241007105514_/migration.sql
  prisma/migrations/20241007110241_/migration.sql
  prisma/migrations/20241011075219_/migration.sql
  prisma/migrations/20241012151517_/migration.sql
  prisma/migrations/migration_lock.toml
  prisma/schema.prisma
  src/app.module.ts
  src/app.service.ts
  src/experience/constants/experience.constant.ts
  src/experience/dto/response-experience.dto.ts
  src/experience/dto/update-experience.dto.ts
  src/experience/entities/experience.entity.ts
  src/experience/experience.controller.spec.ts
  src/experience/experience.controller.ts
  src/experience/experience.module.ts
  src/experience/experience.service.spec.ts
  src/experience/experience.service.ts
  src/main.ts
  src/points/dto/response-point.dto.ts
  src/points/dto/update-point.dto.ts
  src/points/entities/point.entity.ts
  src/points/points.controller.spec.ts
  src/points/points.controller.ts
  src/points/points.module.ts
  src/points/points.service.spec.ts
  src/points/points.service.ts
  src/prisma/prisma.module.ts
  src/prisma/prisma.service.ts
  src/users/dto/create-user.dto.ts
  src/users/dto/response-user.dto.ts
  src/users/dto/update-user.dto.ts
  src/users/users.controller.spec.ts
  src/users/users.controller.ts
  src/users/users.module.ts
  src/users/users.service.spec.ts
  src/users/users.service.ts
Labels: feat, API, setting

#17 quizzes API , sections API 작성
  .vscode/launch.json
  Dockerfile
  package-lock.json
  prisma/migrations/20241002124553_init/migration.sql
  prisma/migrations/20241004045337_camel_case/migration.sql
  prisma/migrations/20241004061240_add_view/migration.sql
  prisma/migrations/20241007054035_change_table_name/migration.sql
  prisma/migrations/20241007085636_create_sectons_relation/migration.sql
  prisma/migrations/20241007105500_create_enum_part/migration.sql
  prisma/migrations/20241009080154_create_category_enum/migration.sql
  prisma/migrations/20241015103208_refec_model_type/migration.sql
  prisma/schema.prisma
  src/app.module.ts
  src/common/pipes/positive-int/positive-int.pipe.spec.ts
  src/common/pipes/positive-int/positive-int.pipe.ts
  src/main.ts
  src/prisma/prisma.module.ts
  src/prisma/prisma.service.spec.ts
  src/quizzes/dto/create-quiz.dto.ts
  src/quizzes/dto/query-quiz.dto.ts
  src/quizzes/dto/update-quiz.dto.ts
  src/quizzes/entities/quizzes.entity.ts
  src/quizzes/quizzes.controller.spec.ts
  src/quizzes/quizzes.controller.ts
  src/quizzes/quizzes.module.ts
  src/quizzes/quizzes.service.spec.ts
  src/quizzes/quizzes.service.ts
  src/sections/dto/create-section.dto.ts
  src/sections/dto/update-section.dto.ts
  src/sections/entities/section.entity.ts
  src/sections/sections.controller.spec.ts
  src/sections/sections.controller.ts
  src/sections/sections.module.ts
  src/sections/sections.service.spec.ts
  src/sections/sections.service.ts
Labels: feat, API

#19 Users와 관련된 폴더들 통합
  src/app.module.ts
  src/experience/entities/experience.entity.ts
  src/experience/experience.controller.spec.ts
  src/experience/experience.controller.ts
  src/experience/experience.module.ts
  src/points/entities/point.entity.ts
  src/points/points.controller.spec.ts
  src/points/points.controller.ts
  src/points/points.module.ts
  src/points/points.service.spec.ts
  src/users/constants/user-experience.constant.ts
  src/users/controllers/user-experience.controller.spec.ts
  src/users/controllers/user-experience.controller.ts
  src/users/controllers/user-point.controller.spec.ts
  src/users/controllers/user-point.controller.ts
  src/users/controllers/users.controller.spec.ts
  src/users/controllers/users.controller.ts
  src/users/dtos/create-user.dto.ts
  src/users/dtos/response-experience.dto.ts
  src/users/dtos/response-point.dto.ts
  src/users/dtos/response-user.dto.ts
  src/users/dtos/update-experience.dto.ts
  src/users/dtos/update-point.dto.ts
  src/users/dtos/update-user.dto.ts
  src/users/modules/user-experience.module.ts
  src/users/modules/user-point.module.ts
  src/users/modules/users.module.ts
  src/users/services/user-experience.service.spec.ts
  src/users/services/user-experience.service.ts
  src/users/services/user-point.service.spec.ts
  src/users/services/user-point.service.ts
  src/users/services/users.service.spec.ts
  src/users/services/users.service.ts
Labels: setting

#21 User Swagger 문서 생성
  prisma/migrations/20241021064303_/migration.sql
  prisma/schema.prisma
  src/main.ts
  src/users/controllers/user-experience.controller.ts
  src/users/controllers/user-point.controller.ts
  src/users/controllers/users.controller.ts
  src/users/dtos/create-user.dto.ts
  src/users/dtos/response-experience.dto.ts
  src/users/dtos/response-point.dto.ts
  src/users/dtos/response-user.dto.ts
  src/users/dtos/update-experience.dto.ts
  src/users/dtos/update-point.dto.ts
  src/users/dtos/update-user.dto.ts
  src/users/services/user-experience.service.ts
  src/users/services/user-point.service.ts
  src/users/services/users.service.ts
  src/users/swagger-dacorator/delete-user-decorators.ts
  src/users/swagger-dacorator/get-all-users-decorators.ts
  src/users/swagger-dacorator/get-user-decorators.ts
  src/users/swagger-dacorator/get-user-experience-decorators.ts
  src/users/swagger-dacorator/get-user-point-decorators.ts
  src/users/swagger-dacorator/patch-user-decorators.ts
  src/users/swagger-dacorator/patch-user-experience-decorators.ts
  src/users/swagger-dacorator/patch-user-point-decorators.ts
  src/users/swagger-dacorator/post-user-decorators.ts
Labels: docs, feat, API
