Repository modern-agile-team/8term-coko-back, pull requests merged in 2024-11, with the labels that each got.

#20 Items api 작성
  package-lock.json
  prisma/migrations/20241101083615_ultradelete/migration.sql
  prisma/migrations/20241107031415_241107/migration.sql
  prisma/migrations/20241113034527_/migration.sql
  prisma/schema.prisma
  src/app.module.ts
  src/items/dto/item-changeStatus.dto.ts
  src/items/items.controller.ts
  src/items/items.module.ts
  src/items/items.service.ts
Labels: feat, API, refactor

#27 진행도 response 변경
  src/progress/progress.service.ts
Labels: modify

#32 Modify/#31/sections findone
  src/sections/sections.service.ts
  src/sections/sections.swagger.ts
Labels: modify, API

#34 새로운 quizze api , 정답을 틀렸던 문제들을 받기
  src/quizzes/quizzes.controller.ts
  src/quizzes/quizzes.service.ts
  src/quizzes/quizzes.swagger.ts
Labels: feat, API
