Repository modern-agile-team/8term-coko-back, pull requests merged in 2025-02, with the labels that each got.

#92 modify/#84/엔드포인트url 수정 및 스웨거태그 변경
  src/part-progress/part-progress.controller.ts
Labels: modify, API

#93 feat/#91/admin 토큰 만료 시간 연장
  src/auth/services/token.service.ts
Labels: modify

#95 parts/status를 complet 로 만드는 api
  .github/workflows/main.yml
  src/part-progress/part-progress.controller.ts
  src/part-progress/part-progress.repository.ts
  src/part-progress/part-progress.service.ts
  src/part-progress/part-progress.swagger.ts
  src/parts/parts.repository.ts
  src/parts/parts.service.ts
  src/parts/parts.swagger.ts
Labels: feat, API

#96 modify/#94/api 다시 소생
  src/part-progress/part-progress.controller.ts
Labels: bug, API

#99 랭킹 응답 데이터 수정
  .github/workflows/main.yml
  src/ranking/dtos/res-my-ranking.dto.ts
  src/ranking/rankings.service.ts
Labels: modify

#101 출석체크 api 작업
  prisma/migrations/20250205044537_create_attendance/migration.sql
  prisma/schema.prisma
  src/app.module.ts
  src/attendance/attendance.controller.ts
  src/attendance/attendance.module.ts
  src/attendance/attendance.repository.ts
  src/attendance/attendance.service.ts
  src/attendance/attendance.swagger.ts
  src/attendance/dtos/attendance-date-query.dto.ts
  src/attendance/dtos/res-monthly-attendance.dto.ts
  src/attendance/entities/attendance.entity.ts
Labels: feat, API

#100 locked상태의 파트를 완료하지 못하게 변경 + 파트 추가시 디폴트 상태 조건을 추가
  src/part-progress/part-progress.module.ts
  src/part-progress/part-progress.repository.ts
  src/part-progress/part-progress.service.ts
  src/parts/parts.service.ts
Labels: modify

#47 [Feature] 상점 유저아이템 API
  .github/workflows/main.yml
  Dockerfile
  docker-compose.yml
  package-lock.json
  package.json
  prisma/migrations/20241211063714_add_item_category/migration.sql
  prisma/migrations/20250117113324_add_item_tables/migration.sql
  prisma/schema.prisma
  src/app.module.ts
  src/items/dto/change-item-status.dto.ts
  src/items/dto/item-changeStatus.dto.ts
  src/items/items.controller.ts
  src/items/items.module.ts
  src/items/items.service.ts
  src/items/items.swagger.ts
  src/main.ts
  src/parts/dto/update-part.dto.ts
  src/sections/dto/update-section.dto.ts
  src/users/controllers/user-items.controller.spec.ts
  src/users/controllers/user-items.controller.ts
  src/users/dtos/buy-userItems.dto.ts
  src/users/dtos/equip-useritem.dto.ts
  src/users/dtos/response-item.dto.ts
  src/users/entities/user-item.entity.ts
  src/users/modules/user-items.module.ts
  src/users/services/user-items.service.spec.ts
  src/users/services/user-items.service.ts
  src/users/swagger-dacorator/get-user-items.decorators.ts
  src/users/swagger-dacorator/patch-user-items.decorator.ts
  src/users/swagger-dacorator/post-user-items.decorators.ts
  src/users/swagger-dacorator/put-user-items.decorators.ts
Labels: feat, API, refactor

#107 도커파일 생성
  .Dockerfile
  .github/workflows/main.yml
  docker-compose.yml
Labels: API

#108 modify/#102/도커파일 명 수정
  dockerfile
Labels: modify

#106 유저의 오늘의 일일퀘스트 API 작성
  .github/workflows/main.yml
  package-lock.json
  package.json
  prisma/migrations/20250205050600_create_user_daily_quest/migration.sql
  prisma/schema.prisma
  src/daily-quests/daily-quests.controller.ts
  src/daily-quests/daily-quests.interface.ts
  src/daily-quests/daily-quests.module.ts
  src/daily-quests/daily-quests.repository.ts
  src/daily-quests/daily-quests.service.ts
  src/daily-quests/dto/res-daily-quest.dto.ts
  src/daily-quests/entities/daily-quest.entity.ts
  src/daily-quests/users-daily-quests/const/users-daily-quests.const.ts
  src/daily-quests/users-daily-quests/dto/res-user-daily-quest.dto.ts
  src/daily-quests/users-daily-quests/dto/update-users-daily-quest.dto.ts
  src/daily-quests/users-daily-quests/entities/users-daily-quest.entity.ts
  src/daily-quests/users-daily-quests/users-daily-quest.swagger.ts
  src/daily-quests/users-daily-quests/users-daily-quests.controller.spec.ts
  src/daily-quests/users-daily-quests/users-daily-quests.controller.ts
  src/daily-quests/users-daily-quests/users-daily-quests.interface.ts
  src/daily-quests/users-daily-quests/users-daily-quests.module.ts
  src/daily-quests/users-daily-quests/users-daily-quests.repository.ts
  src/daily-quests/users-daily-quests/users-daily-quests.service.spec.ts
  src/daily-quests/users-daily-quests/users-daily-quests.service.ts
Labels: feat, API

#111 아이템 스웨거 잠시 주석처리
  src/items/items.swagger.ts
Labels: bug, fix

#115 package-lock.json 중복 에러 제거
  .github/workflows/main.yml
  package-lock.json
Labels: bug, fix

#117 랭킹 요청 쿼리값 변수이름 변경
  src/auth/kakao/kakao.startegy.ts
  src/ranking/dtos/ranking-sort.dto.ts
  src/ranking/entities/ranking.entity.ts
  src/ranking/utils/filter-utils.ts
  src/ranking/utils/sort-utils.ts
Labels: modify, API

#118 카카오 로그인 생성
  package-lock.json
  package.json
  src/auth/auth.controller.ts
  src/auth/auth.module.ts
  src/auth/dtos/social-user-info.dto.ts
  src/auth/google/google.strategy.ts
  src/auth/kakao/kakao.startegy.ts
  src/auth/services/auth.service.ts
  src/users/dtos/create-user.dto.ts
Labels: feat, API

#121 깃허브 로그인 생성 및 회원 탈퇴 생성
  package-lock.json
  package.json
  src/auth/auth.controller.ts
  src/auth/auth.module.ts
  src/auth/services/auth.service.ts
  src/auth/services/token.service.ts
  src/auth/social/github.strategy.ts
  src/auth/social/google.strategy.ts
  src/auth/social/kakao.startegy.ts
  src/users/controllers/users.controller.ts
  src/users/modules/users.module.ts
  src/users/repositories/users.reposirory.ts
  src/users/services/users.service.ts
Labels: feat, API

#124 Feat/#105/items api 작업
  package-lock.json
  src/auth/google/google-user.dto.ts
  src/auth/google/google.strategy.ts
  src/auth/kakao/kakao.startegy.ts
  src/items/dto/category-query.dto.ts
  src/items/dto/change-item-status.dto.ts
  src/items/dto/create-item.dto.ts
  src/items/dto/item-changeStatus.dto.ts
  src/items/dto/pagination-query.dto.ts
  src/items/dto/update-item.dto.ts
  src/items/items.controller.ts
  src/items/items.module.ts
  src/items/items.service.ts
  src/items/items.swagger.ts
  src/main.ts
  src/users/controllers/user-items.controller.ts
Labels: feat, API

#122 user daily quest update api 삭제 및 서버 이벤트 확인으로 변경
  package-lock.json
  package.json
  prisma/migrations/20250212021729_update_daily_quest/migration.sql
  prisma/schema.prisma
  src/app.module.ts
  src/daily-quests/daily-quests.interface.ts
  src/daily-quests/dto/create-daily-quest.dto.ts
  src/daily-quests/dto/res-daily-quest.dto.ts
  src/daily-quests/entities/daily-quest.entity.ts
  src/daily-quests/users-daily-quests/dto/res-user-daily-quest.dto.ts
  src/daily-quests/users-daily-quests/dto/update-users-daily-quest.dto.ts
  src/daily-quests/users-daily-quests/users-daily-quests.controller.ts
  src/daily-quests/users-daily-quests/users-daily-quests.module.ts
  src/daily-quests/users-daily-quests/users-daily-quests.service.ts
  src/progress/progress.repository.ts
  src/progress/progress.service.ts
Labels: modify, API

#128 유저의 일일퀘스트 진행도가 일일퀘스트 목표치를 상회 하던 에러 수정
  src/daily-quests/users-daily-quests/dto/update-users-daily-quest.dto.ts
  src/daily-quests/users-daily-quests/users-daily-quests.service.ts
Labels: bug, fix

#125 refactor/#105/iItems api - 아이템 카테고리별로 조회, 페이지네이션 적용
  src/items/categories.repository.ts
  src/items/dto/create-item.dto.ts
  src/items/dto/items-pagination-query.dto.ts
  src/items/dto/items-pagination-response.dto.ts
  src/items/dto/pagination-query.dto.ts
  src/items/dto/update-item.dto.ts
  src/items/items.controller.ts
  src/items/items.module.ts
  src/items/items.repository.ts
  src/items/items.service.ts
  src/ranking/dtos/ranking-pagination-res.dto.ts
Labels: refactor

#134 admin 토큰 이름 변경
  src/admin/admin.controller.ts
  src/admin/admin.module.ts
  src/admin/admin.service.ts
  src/app.module.ts
  src/auth/jwt/jwt.startegy.ts
  src/auth/services/cookie.service.ts
  src/auth/services/token.service.ts
Labels: bug, fix

#135 fix/#132/PATCH 오류 해결
  src/items/categories.repository.ts
  src/items/dto/items-pagination-query.dto.ts
  src/items/dto/update-item.dto.ts
  src/items/items.controller.ts
  src/items/items.service.ts
Labels: bug, fix, API

#137 유저 도전과제(UserChallenge) 페이지네이션API 및 생성 로직
  prisma/migrations/20250214022246_update_challenge/migration.sql
  prisma/migrations/20250216102015_update_badge_name_add_unique/migration.sql
  prisma/migrations/20250217102747_create_challenge/migration.sql
  prisma/migrations/20250217104543_creaet_user_challenge/migration.sql
  prisma/schema.prisma
  src/app.module.ts
  src/challenge/challenge.controller.spec.ts
  src/challenge/challenge.controller.ts
  src/challenge/challenge.module.ts
  src/challenge/challenge.service.ts
  src/challenge/dto/res-challenge-pagination.dto.ts
  src/challenge/dto/update-challenge.dto.ts
  src/challenge/entities/challenge.entity.ts
  src/challenges/challenges.controller.spec.ts
  src/challenges/challenges.controller.ts
  src/challenges/challenges.interface.ts
  src/challenges/challenges.module.ts
  src/challenges/challenges.repository.ts
  src/challenges/challenges.service.spec.ts
  src/challenges/challenges.service.ts
  src/challenges/challenges.swagger.ts
  src/challenges/dto/create-challenges.dto.ts
  src/challenges/dto/query-challenges.dto.ts
  src/challenges/dto/res-challenges-pagination.dto.ts
  src/challenges/dto/res-challenges.dto.ts
  src/challenges/dto/update-challenges.dto.ts
  src/challenges/user-challenges/dto/create-user-challenges.dto.ts
  src/challenges/user-challenges/dto/res-user-challenges-pagination.dto.ts
  src/challenges/user-challenges/dto/res-user-challenges.dto.ts
  src/challenges/user-challenges/dto/update-user-challenges.dto.ts
  src/challenges/user-challenges/user-challenges.controller.spec.ts
  src/challenges/user-challenges/user-challenges.controller.ts
  src/challenges/user-challenges/user-challenges.interface.ts
  src/challenges/user-challenges/user-challenges.module.ts
  src/challenges/user-challenges/user-challenges.repository.ts
  src/challenges/user-challenges/user-challenges.service.spec.ts
  src/challenges/user-challenges/user-challenges.service.ts
  src/daily-quests/daily-quests.controller.ts
  src/users/repositories/users.reposirory.ts
  src/users/services/users.service.ts
Labels: feat, API, refactor

#138 SSE 생성 및 userHp 로직 수정
  prisma/migrations/20250218081246_fix_user_hp_storage/migration.sql
  prisma/schema.prisma
  src/admin/admin.controller.ts
  src/app.module.ts
  src/sse/sse.controller.ts
  src/sse/sse.module.ts
  src/sse/sse.service.ts
  src/users/constants/user-attendance.constant.ts
  src/users/constants/user-experience.constant.ts
  src/users/constants/user-hp.constant.ts
  src/users/controllers/user-hp.controller.ts
  src/users/dtos/res-user-hp.dto.ts
  src/users/dtos/update-hp.dto.ts
  src/users/events/user-hp.event.ts
  src/users/modules/user-hp.module.ts
  src/users/modules/users-core.module.ts
  src/users/repositories/user-hp.repository.ts
  src/users/services/user-hp.service.ts
  src/users/swaggers/user-hp.swagger.ts
Labels: feat, API

#144 섹션n 클리어시 유저-도전과제를 completed로 변경
  prisma/migrations/20250218122110_add_challenge_type/migration.sql
  prisma/migrations/20250219015452_add_unique_key/migration.sql
  prisma/schema.prisma
  src/auth/jwt/jwt.startegy.ts
  src/challenges/challenges.interface.ts
  src/challenges/challenges.module.ts
  src/challenges/challenges.repository.ts
  src/challenges/const/challenges.constant.ts
  src/challenges/dto/create-challenges.dto.ts
  src/challenges/dto/res-challenges.dto.ts
  src/challenges/events/challenges.event.ts
  src/challenges/section-clear-challenges.service.ts
  src/challenges/user-challenges/dto/update-user-challenges.dto.ts
  src/challenges/user-challenges/user-challenges.module.ts
  src/challenges/user-challenges/user-challenges.repository.ts
  src/challenges/user-challenges/user-challenges.service.ts
  src/part-progress/part-progress.repository.ts
  src/part-progress/part-progress.service.ts
Labels: feat

#146 문의 api 생성
  .github/ISSUE_TEMPLATE/-이슈-템플릿.md
  prisma/migrations/20250220123335_create_opinion/migration.sql
  prisma/schema.prisma
  src/admin/admin.swagger.ts
  src/app.module.ts
  src/attendance/attendance.swagger.ts
  src/auth/auth.module.ts
  src/auth/jwt/jwt.strategy.ts
  src/ranking/rankings.controller.ts
  src/ranking/rankings.swagger.ts
  src/ranking/user-rankings.controller.ts
  src/users/constants/user-hp.constant.ts
  src/users/controllers/user-hp.controller.ts
  src/users/opinions/dtos/create-opinion.dto.ts
  src/users/opinions/dtos/res-my-opinions.dto.ts
  src/users/opinions/dtos/res-opinions.dto.ts
  src/users/opinions/opinion.interface.ts
  src/users/opinions/opinions.controller.ts
  src/users/opinions/user-opinions.controller.ts
  src/users/opinions/user-opinions.module.ts
  src/users/opinions/user-opinions.repository.ts
  src/users/opinions/user-opinions.service.ts
  src/users/opinions/user-opinions.swagger.ts
  src/users/services/user-hp.service.ts
  src/users/swaggers/user-hp.swagger.ts
Labels: feat, API

#152 문의하기 글자수 변경 및 폴더위치 변경
  src/app.module.ts
  src/opinions/dtos/create-opinion.dto.ts
  src/opinions/dtos/res-my-opinions.dto.ts
  src/opinions/dtos/res-opinions.dto.ts
  src/opinions/opinion.interface.ts
  src/opinions/opinions.controller.ts
  src/opinions/opinions.module.ts
  src/opinions/opinions.repository.ts
  src/opinions/opinions.service.ts
  src/opinions/opinions.swagger.ts
  src/opinions/user-opinions.controller.ts
Labels: fix

#154 레벨클리어 도전과제 세부로직 작성
  src/challenges/challenges.interface.ts
  src/challenges/challenges.module.ts
  src/challenges/challenges.repository.ts
  src/challenges/const/challenges.constant.ts
  src/challenges/dto/create-challenges.dto.ts
  src/challenges/dto/res-challenges.dto.ts
  src/challenges/events/challenges.event.ts
  src/challenges/level-clear-challenges.service.ts
  src/challenges/section-clear-challenges.service.ts
  src/challenges/user-challenges/user-challenges.interface.ts
  src/challenges/user-challenges/user-challenges.repository.ts
  src/part-progress/part-progress.service.ts
  src/users/controllers/user-experience.controller.ts
  src/users/services/user-experience.service.ts
Labels: feat

#150 총 정답 수 랭킹 생성
  prisma/migrations/20250224070729_create_total_correct_answer_column/migration.sql
  prisma/schema.prisma
  src/progress/progress.service.ts
  src/ranking/dtos/ranking-sort.dto.ts
  src/ranking/dtos/user-ranking.dto.ts
  src/ranking/entities/ranking.entity.ts
  src/ranking/ranking.constant.ts
  src/ranking/rankings.event.ts
  src/ranking/rankings.module.ts
  src/ranking/rankings.repository.ts
  src/ranking/rankings.service.ts
  src/ranking/utils/filter-utils.ts
  src/ranking/utils/sort-utils.ts
  src/users/dtos/response-user.dto.ts
  src/users/entities/user.entity.ts
  src/users/repositories/users.reposirory.ts
Labels: feat

#160 연속 출석 도전과제 생성
  src/attendance/attendance.module.ts
  src/attendance/attendance.repository.ts
  src/attendance/attendance.service.ts
  src/challenges/attendance-streak-challenges.service.ts
  src/challenges/challenges.module.ts
  src/challenges/const/challenges.constant.ts
  src/challenges/events/challenges.event.ts
  src/challenges/user-challenges/user-challenges.repository.ts
Labels: feat

#162 메서드 파라미터 순서변경
  src/challenges/level-clear-challenges.service.ts
Labels: bug, fix

#165 bugfix/#164/sectionId를 조회할때 추가
  src/challenges/section-clear-challenges.service.ts
  src/part-progress/part-progress.repository.ts
Labels: bug, fix

#163 GET /users/me/challenges api 페이지네이션 요청에 정렬 추가
  src/challenges/challenges.repository.ts
  src/challenges/challenges.service.ts
  src/challenges/dto/query-challenges.dto.ts
  src/challenges/dto/res-challenges.dto.ts
  src/challenges/user-challenges/user-challenges.repository.ts
  src/challenges/user-challenges/user-challenges.service.ts
Labels: feat, API

#175 랭킹달성 enum 분리
  prisma/migrations/20250228081752_add_challenge_enum/migration.sql
  prisma/schema.prisma
  src/challenges/const/challenges.constant.ts
  src/challenges/events/challenges.event.ts
  src/challenges/ranking-challenges.service.ts
  src/common/constants/rankings-constants.ts
  src/daily-quests/users-daily-quests/const/users-daily-quests.const.ts
  src/main.ts
  src/ranking/rankings.controller.ts
  src/ranking/rankings.service.ts
  src/ranking/rankings.swagger.ts
  tsconfig.json
Labels: feat

#169 "처음 아이템을 구매하다!" 도전과제 세부로직 작성
  src/challenges/challenges.module.ts
  src/challenges/const/challenges.constant.ts
  src/challenges/events/challenges.event.ts
  src/challenges/first-item-buy.challenges.service.ts
  src/users/services/user-items.service.ts
Labels: feat
