Repository modern-agile-team/8term-coko-back, pull requests merged in 2025-01, with the labels that each got.

#57 jwt 인증에 관련된 기능들 생성
  .github/workflows/main.yml
  Dockerfile
  docker-compose.yml
  package-lock.json
  package.json
  src/auth/auth.controller.ts
  src/auth/auth.module.ts
  src/auth/auth.service.ts
  src/auth/google.strategy.ts
  src/auth/jwt/jwt.dto.ts
  src/auth/jwt/jwt.startegy.ts
  src/auth/redis/redis.module.ts
  src/auth/redis/redis.service.ts
  src/auth/services/auth.service.ts
  src/auth/services/cookie.service.ts
  src/auth/services/token.service.ts
  src/main.ts
  src/users/dtos/response-user.dto.ts
  src/users/modules/users.module.ts
  src/users/services/user-experience.service.ts
  src/users/services/user-point.service.ts
  src/users/services/users.service.ts
Labels: feat, fix, API

#56 유저또는 파트 생성시 디폴트 파트 진행도를 생성
  src/app.module.ts
  src/part-progress/dto/create-part-progress.dto.ts
  src/part-progress/part-progress.module.ts
  src/part-progress/part-progress.service.ts
  src/parts/parts.controller.ts
  src/parts/parts.module.ts
  src/parts/parts.repository.ts
  src/parts/parts.service.ts
  src/users/services/users.service.ts
Labels: feat, modify

#62 유저 생명력 api
  .github/workflows/main.yml
  prisma/migrations/20250103050017_create_user_hp_and_change_user_schema/migration.sql
  prisma/migrations/20250103051335_relation_user_hp/migration.sql
  prisma/migrations/20250103052032_change_user_hp_table_name/migration.sql
  prisma/schema.prisma
  src/app.module.ts
  src/sections/sections.service.ts
  src/users/constants/user-experience.constant.ts
  src/users/controllers/user-hp.controller.spec.ts
  src/users/controllers/user-hp.controller.ts
  src/users/dtos/create-user.dto.ts
  src/users/dtos/res-user-hp.dto.ts
  src/users/dtos/response-user.dto.ts
  src/users/dtos/update-hp.dto.ts
  src/users/entities/user-hp.entity.ts
  src/users/modules/user-hp.module.ts
  src/users/modules/users-core.module.ts
  src/users/modules/users.module.ts
  src/users/repositories/user-hp.repository.ts
  src/users/services/user-hp.service.spec.ts
  src/users/services/user-hp.service.ts
  src/users/services/users.service.ts
  src/users/swaggers/user-hp.swagger.ts
Labels: feat, modify, API

#60 admin 권한을 확인하는 api 생성
  .github/workflows/main.yml
  package-lock.json
  package.json
  prisma/migrations/20250107081153_create_admin/migration.sql
  prisma/schema.prisma
  src/admin/admin.controller.ts
  src/admin/admin.module.ts
  src/admin/admin.repository.ts
  src/admin/admin.service.ts
  src/admin/admin.swagger.ts
  src/admin/login-admin.dto.ts
  src/app.module.ts
  src/auth/auth.controller.ts
  src/auth/auth.module.ts
  src/auth/guard/admin.guard.ts
  src/auth/jwt/jwt.startegy.ts
  src/auth/services/cookie.service.ts
  src/auth/services/token.service.ts
  src/main.ts
  src/parts/parts.controller.ts
  src/quizzes/quizzes.controller.ts
  src/quizzes/quizzes.module.ts
  src/sections/sections.controller.ts
Labels: feat, API

#69 app 모듈에서 section모듈과 userscore모듈 순서변경
  src/app.module.ts
Labels: bug, fix

#72 access토큰값을 넣는 스웨거 authorize 버튼(쿠키)
  src/main.ts
  src/users/controllers/user-hp.controller.ts
  src/users/dtos/res-user-hp.dto.ts
  src/users/dtos/update-hp.dto.ts
  src/users/swaggers/user-hp.swagger.ts
Labels: feat

#67 메인페이지 section, part, part-status 의 status 값 페이지네이션으로 제공하는 api
  src/app.module.ts
  src/common/type/type.ts
  src/pagination/pagination.interface.ts
  src/pagination/pagination.module.ts
  src/pagination/pagination.service.spec.ts
  src/pagination/pagination.service.ts
  src/parts/const/example-parts.ts
  src/parts/dto/res-part-status.dto.ts
  src/parts/dto/res-part.dto.ts
  src/parts/parts.controller.ts
  src/parts/parts.swagger.ts
  src/sections/const/section.const.ts
  src/sections/dto/create-section.dto.ts
  src/sections/dto/query-section.dto.ts
  src/sections/dto/res-pagination-of-section-parts.dto.ts
  src/sections/dto/res-section-parts.dto.ts
  src/sections/dto/res-section.dto.ts
  src/sections/sections.controller.ts
  src/sections/sections.module.ts
  src/sections/sections.repository.ts
  src/sections/sections.service.ts
  src/sections/sections.swagger.ts
  src/sections/users-sections.controller.ts
Labels: feat, modify, API

#75 sections/{id} API 복구 및 수정
  src/sections/sections.controller.ts
  src/sections/sections.service.ts
  src/sections/sections.swagger.ts
Labels: bug, fix, modify

#76 GET /section/id 에서 찾을 수 없는 404상태에 500으로 띄우던 에러 수정
  src/sections/sections.service.ts
Labels: bug, fix

#78 fix/#77/로그아웃 api 오타 수정
  .github/workflows/main.yml
  src/auth/auth.controller.ts
Labels: bug, fix

#81 section 엔드포인트 순서변경
  .github/workflows/main.yml
  src/common/pipes/positive-int/positive-int.pipe.ts
  src/sections/sections.controller.ts
Labels: bug, fix

#82 일일퀘스트 기본 crud 작성
  prisma/migrations/20250122075156_daily_quest_create/migration.sql
  prisma/migrations/20250122085602_add_created_at_updated_at/migration.sql
  prisma/schema.prisma
  src/app.module.ts
  src/daily-quests/daily-quest.swagger.ts
  src/daily-quests/daily-quests.controller.spec.ts
  src/daily-quests/daily-quests.controller.ts
  src/daily-quests/daily-quests.interpace.ts
  src/daily-quests/daily-quests.module.ts
  src/daily-quests/daily-quests.repository.ts
  src/daily-quests/daily-quests.service.spec.ts
  src/daily-quests/daily-quests.service.ts
  src/daily-quests/dto/create-daily-quest.dto.ts
  src/daily-quests/dto/res-daily-quest.dto.ts
  src/daily-quests/dto/update-daily-quest.dto.ts
  src/daily-quests/entities/daily-quest.entity.ts
Labels: feat, API

#79 Feat/#71/create ranking api
  .github/workflows/main.yml
  src/app.module.ts
  src/common/constants/rankings-constants.ts
  src/main.ts
  src/pagination/dtos/offset-pagination-res.dto.ts
  src/ranking/dtos/ranking-pagination-res.dto.ts
  src/ranking/dtos/ranking-query.dto.ts
  src/ranking/dtos/res-my-ranking.dto.ts
  src/ranking/dtos/user-rankings.dto.ts
  src/ranking/entities/ranking.entity.ts
  src/ranking/ranking.swagger.ts
  src/ranking/rankings.controller.ts
  src/ranking/rankings.module.ts
  src/ranking/rankings.repository.ts
  src/ranking/rankings.service.ts
  src/ranking/utils/filter-utils.ts
  src/ranking/utils/sort-utils.ts
  src/users/modules/users.module.ts
  src/users/repositories/users.reposirory.ts
  src/users/services/users.service.ts
Labels: feat, API

#85 url - users/:id -> users/me
  src/part-progress/part-progress.controller.ts
  src/parts/parts.controller.ts
  src/progress/dto/res-progress.dto.ts
  src/progress/progress.controller.ts
  src/progress/progress.swagger.ts
  src/quizzes/quizzes.controller.ts
  src/quizzes/quizzes.module.ts
  src/quizzes/users-quizzes.controller.ts
  src/sections/sections.controller.ts
  src/sections/users-sections.controller.ts
Labels: modify, API

#86 url - users/:id -> users/me
  src/users/controllers/user-experience.controller.ts
  src/users/controllers/user-hp.controller.ts
  src/users/controllers/user-point.controller.ts
  src/users/controllers/users.controller.ts
  src/users/services/users.service.ts
Labels: modify, API
