Repository modern-agile-team/8term-coko-back, pull requests merged in 2025-03, with the labels that each got.

#177 유저도전과제 orderby 옵션을 더 명확하게 정의
  src/challenges/user-challenges/user-challenges.repository.ts
Labels: refactor

#178 타입별 정렬 내림차순을 올림차순으로 변경
  src/challenges/user-challenges/user-challenges.repository.ts
Labels: refactor

#172 fix/ user-items : GET pagination, 장착 api 생성 + coko 상점 default값 생성
  package-lock.json
  package.json
  prisma/migrations/migration_lock.toml
  src/items/entities/item.entity.ts
  src/items/items.service.ts
  src/items/items.swagger.ts
  src/users/controllers/user-experience.controller.ts
  src/users/controllers/user-items.controller.ts
  src/users/controllers/user-point.controller.ts
  src/users/controllers/users.controller.ts
  src/users/dtos/response-item.dto.ts
  src/users/dtos/response-userItems-pagination.dto.ts
  src/users/dtos/response-useritem.dto.ts
  src/users/dtos/userItems-pagination-query.dto.ts
  src/users/dtos/userItems-pagination-res.dto.ts
  src/users/dtos/userItems-query.dto.ts
  src/users/entities/user-item.entity.ts
  src/users/modules/user-items.module.ts
  src/users/repositories/user-items.repository.ts
  src/users/services/user-items.service.ts
  src/users/services/users.service.ts
  src/users/swagger-dacorator/get-user-items.decorators.ts
  src/users/swagger-decorator/delete-user-decorators.ts
  src/users/swagger-decorator/get-all-users-decorators.ts
  src/users/swagger-decorator/get-equipped-user-items.decorators.ts
  src/users/swagger-decorator/get-user-decorators.ts
  src/users/swagger-decorator/get-user-experience-decorators.ts
  src/users/swagger-decorator/get-user-items.decorators.ts
  src/users/swagger-decorator/get-user-point-decorators.ts
  src/users/swagger-decorator/patch-user-decorators.ts
  src/users/swagger-decorator/patch-user-experience-decorators.ts
  src/users/swagger-decorator/patch-user-items.decorator.ts
  src/users/swagger-decorator/patch-user-point-decorators.ts
  src/users/swagger-decorator/post-user-decorators.ts
  src/users/swagger-decorator/post-user-items.decorators.ts
  src/users/swagger-decorator/put-user-items.decorators.ts
Labels: docs, feat, fix, API

#179 "처음으로 문제를 틀림" 도전과제 세부로직
  src/challenges/challenges.module.ts
  src/challenges/challenges.repository.ts
  src/challenges/challenges.service.ts
  src/challenges/const/challenges.constant.ts
  src/challenges/dto/query-challenges.dto.ts
  src/challenges/events/challenges.event.ts
  src/challenges/first-wrong-answer.challenges.service.ts
  src/challenges/user-challenges/user-challenges.repository.ts
  src/challenges/user-challenges/user-challenges.service.ts
  src/daily-quests/users-daily-quests/users-daily-quests.service.ts
  src/progress/progress.service.ts
Labels: feat

#180 랭킹 도전과제 생성
  src/challenges/events/challenges.event.ts
  src/challenges/ranking-challenges.service.ts
  src/challenges/user-challenges/user-challenges.repository.ts
  src/common/constants/rankings-constants.ts
  src/common/function/time.helper.ts
  src/ranking/dtos/res-season-end-time.dto.ts
  src/ranking/rankings.controller.ts
  src/ranking/rankings.service.ts
  src/ranking/rankings.swagger.ts
Labels: feat

#182 유저 아이템 장착여부 조회 api의 res정보데이터 변경
  src/items/dto/response-item.dto.ts
  src/items/items.service.ts
  src/users/controllers/user-items.controller.ts
  src/users/dtos/response-user-equipped.dto.ts
  src/users/dtos/response-userItems-pagination.dto.ts
  src/users/swagger-decorator/get-equipped-user-items.decorators.ts
  src/users/swagger-decorator/get-user-items.decorators.ts
Labels: refactor

#183 #181의 유저아이템 response DTO에 서브카테고리 아이디 값 추가
  src/users/dtos/response-user-equipped.dto.ts
Labels: feat

#185 이벤트 상수 모으는 작업
  src/attendance/attendance.service.ts
  src/challenges/const/challenges.constant.ts
  src/challenges/events/challenges.event.ts
  src/common/constants/event-constants.ts
  src/daily-quests/users-daily-quests/users-daily-quests.service.ts
  src/part-progress/part-progress.service.ts
  src/progress/progress.service.ts
  src/ranking/rankings.service.ts
  src/users/services/user-experience.service.ts
  src/users/services/user-hp.service.ts
  src/users/services/user-items.service.ts
Labels: fix

#191 주간 랭킹 집계 이벤트명 수정
  src/challenges/events/challenges.event.ts
  src/ranking/rankings.event.ts
  src/users/controllers/user-experience.controller.ts
  src/users/controllers/user-point.controller.ts
  src/users/controllers/users.controller.ts
  src/users/events/user-hp.event.ts
Labels: fix

#195 fix/#194/랭킹 페이지내이션 로직 수정
  src/ranking/rankings.service.ts
Labels: bug, fix

#196 레벨 랭킹 정렬 조건 수정
  src/ranking/utils/filter-utils.ts
Labels: fix

#199 오늘의 퀘스트 완료시 유저에게 포인트지급 + 완료 메시지 보내기
  src/daily-quests/users-daily-quests/events/users-daily-quests.event.ts
  src/daily-quests/users-daily-quests/users-daily-quests.module.ts
  src/daily-quests/users-daily-quests/users-daily-quests.repository.ts
  src/daily-quests/users-daily-quests/users-daily-quests.service.ts
  src/users/user-point/user-point.module.ts
  src/users/user-point/user-point.service.ts
  src/users/users-core.module.ts
Labels: refactor

#203 매주 랭킹 1, 2, 3 등의 데이터 업데이트
  src/challenges/ranking-challenges.service.ts
  src/challenges/user-challenges/user-challenges.repository.ts
  src/ranking/rankings.controller.ts
Labels: fix

#205 회원가입시 email 저장 및 3000포인트 기본 지급
  docker-compose.yml
  prisma/migrations/20250315011740_add_email_column/migration.sql
  prisma/schema.prisma
  src/auth/auth.controller.ts
  src/auth/dtos/social-user-info.dto.ts
  src/auth/google/google-user.dto.ts
  src/auth/google/google.strategy.ts
  src/auth/kakao/kakao.startegy.ts
  src/auth/services/auth.service.ts
  src/auth/social/github.strategy.ts
  src/auth/social/google.strategy.ts
  src/auth/social/kakao.startegy.ts
  src/daily-quests/users-daily-quests/const/users-daily-quests.const.ts
  src/opinions/dtos/create-opinion.dto.ts
  src/opinions/dtos/res-opinions-with-email.dto.ts
  src/opinions/dtos/res-opinions.dto.ts
  src/opinions/opinions.controller.ts
  src/opinions/opinions.module.ts
  src/opinions/opinions.repository.ts
  src/opinions/opinions.service.ts
  src/opinions/user-opinions.controller.ts
  src/ranking/rankings.service.ts
  src/users/dtos/create-user.dto.ts
  src/users/users.service.ts
Labels: fix, API

#209 bugfix 유저 이메일 유니크인덱스 삭제
  prisma/migrations/20250317035046_remove_user_email_unuque/migration.sql
  prisma/migrations/migration_lock.toml
  prisma/schema.prisma
  src/ranking/ranking.constant.ts
Labels: bug, fix

#211 coko back main ver1.0
  .github/workflows/main.yml
  prisma/migrations/20250317042709_add_email_column/migration.sql
  prisma/migrations/migration_lock.toml
  prisma/schema.prisma
  src/ranking/ranking.constant.ts
Labels: setting

#213 cors에 프런트 개발 서버 추가
  src/main.ts
Labels: setting

#218 fix/#217/s3 버전 수정
  package-lock.json
  package.json
  src/s3/log-upload-scheduler.ts
  src/s3/s3.module.ts
  src/s3/s3.service.ts
Labels: fix
